#!/usr/bin/env python3
"""
CiscoQuest: Cisco IOS & Network Security Mastery
100 levels — from user-exec basics to VPN hardening.
Engine: cisco (direct command matching)
Author: arkanzasfeziii
"""

from __future__ import annotations

import os
import random
import sys
import time
from pathlib import Path

try:
    from rich import box
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import Progress, SpinnerColumn, TextColumn
except ImportError:
    os.system(f"{sys.executable} -m pip install rich --quiet")
    from rich.console import Console
    from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

GAME_NAME     = "CiscoQuest"
GAME_SUBTITLE = "Cisco IOS & Network Security Mastery"
SAVE_FILE     = Path.home() / ".ciscoquest_save.json"
ENGINE        = "cisco"

COLORS = {
    "primary":   "bright_blue",
    "secondary": "bright_cyan",
    "success":   "bright_green",
    "error":     "bright_red",
    "warning":   "yellow",
    "info":      "cyan",
    "hacker":    "bright_cyan",
}

RANKS = [
    (0,   "🌐 CLI Rookie",          "Just opened the console"),
    (5,   "📟 Ping Apprentice",     "Testing connectivity"),
    (10,  "🔧 Interface Cadet",     "Configuring interfaces"),
    (15,  "📡 Route Learner",       "Understanding routing"),
    (20,  "🔀 VLAN Padawan",        "Learning switching"),
    (25,  "🛡️ ACL Defender",        "Filtering traffic"),
    (30,  "🌍 OSPF Navigator",      "Dynamic routing"),
    (35,  "🔐 NAT Wizard",          "Address translation"),
    (40,  "⚡ BGP Strategist",      "Inter-domain routing"),
    (45,  "🏗️ STP Architect",       "Spanning tree expert"),
    (50,  "🔒 VPN Engineer",        "Encrypting tunnels"),
    (55,  "📊 QoS Specialist",      "Traffic prioritization"),
    (60,  "🕵️ Security Analyst",    "Hardening devices"),
    (65,  "🚀 Network Engineer",    "Full-stack network ops"),
    (70,  "⚔️ Pen Tester Pro",      "Offensive network skills"),
    (75,  "🎖️ Senior NetEng",       "Mentoring others"),
    (80,  "👑 CCIE Candidate",      "Expert-level mastery"),
    (85,  "🔥 Zero-Day Spotter",    "Finding IOS vulnerabilities"),
    (90,  "🌟 Network Architect",   "Designing enterprise nets"),
    (95,  "🏆 Elite Network God",   "Master of all protocols"),
    (100, "💎 Legendary Netizen",   "The ultimate achievement"),
]

ACHIEVEMENTS = [
    (5,   "🌟 First Ping",         "Completed 5 levels"),
    (10,  "📡 Interface Master",   "Completed 10 levels"),
    (25,  "🔀 Routing Pro",        "Completed 25 levels"),
    (50,  "🛡️ Security Guru",      "Completed 50 levels"),
    (75,  "👑 IOS Expert",         "Completed 75 levels"),
    (100, "💎 Cisco Grandmaster",  "Completed ALL 100 levels!"),
]

# ---------------------------------------------------------------------------
# Levels — 100 real Cisco IOS challenges
# Format: user types the exact IOS command. Accepted list allows minor variations.
# ---------------------------------------------------------------------------
LEVELS = [
    # =========================================================
    # TIER 1 (1-20): IOS CLI Navigation & Basic Configuration
    # =========================================================
    {
        "id": 1, "title": "Enter Privileged Mode",
        "description": "From User EXEC mode (Router>) you need elevated access to run show commands and configure the device.",
        "challenge": "Type the command to enter Privileged EXEC mode.",
        "hint": "It is a single 6-letter word.",
        "solution": "enable",
        "accepted": ["enable", "en"],
        "explanation": "'enable' moves you from User EXEC (>) to Privileged EXEC (#). Always the first step.",
        "points": 10, "category": "basics",
    },
    {
        "id": 2, "title": "Enter Global Configuration Mode",
        "description": "You are in Router# and need to start changing device settings.",
        "challenge": "Type the command to enter Global Configuration mode.",
        "hint": "Think 'configure terminal'.",
        "solution": "configure terminal",
        "accepted": ["configure terminal", "conf t", "conf terminal", "configure t"],
        "explanation": "'configure terminal' (or 'conf t') enters Global Config. Prompt becomes Router(config)#.",
        "points": 10, "category": "basics",
    },
    {
        "id": 3, "title": "Set Hostname",
        "description": "Device identification is critical in large networks. Set the router's name to 'R1'.",
        "challenge": "Set the hostname to R1.",
        "hint": "hostname <name>",
        "solution": "hostname R1",
        "accepted": ["hostname R1", "hostname r1"],
        "explanation": "'hostname R1' changes the CLI prompt to R1(config)# and is stored in running-config.",
        "points": 10, "category": "basics",
    },
    {
        "id": 4, "title": "View Running Configuration",
        "description": "Before making changes you should check what's currently configured.",
        "challenge": "Display the full running configuration.",
        "hint": "show running-config",
        "solution": "show running-config",
        "accepted": ["show running-config", "sh run", "show run"],
        "explanation": "'show running-config' prints the active config in RAM. Changes here are lost on reload unless saved.",
        "points": 10, "category": "basics",
    },
    {
        "id": 5, "title": "Show IOS Version",
        "description": "You need to know the Cisco IOS version running on the device for patch management.",
        "challenge": "Display the IOS version and hardware details.",
        "hint": "show version",
        "solution": "show version",
        "accepted": ["show version", "sh version", "sh ver"],
        "explanation": "'show version' shows IOS version, uptime, hardware model, memory, and license info.",
        "points": 10, "category": "basics",
    },
    {
        "id": 6, "title": "Save the Configuration",
        "description": "Your changes live in RAM. A reload will erase them unless you write them to NVRAM.",
        "challenge": "Save the running configuration to startup configuration.",
        "hint": "copy running-config startup-config",
        "solution": "copy running-config startup-config",
        "accepted": ["copy running-config startup-config", "copy run start", "wr", "write memory"],
        "explanation": "'copy run start' writes RAM config to NVRAM so it survives reloads.",
        "points": 15, "category": "basics",
    },
    {
        "id": 7, "title": "Quick Interface Overview",
        "description": "You need a fast summary of all interface IP addresses and their up/down status.",
        "challenge": "Show a brief summary of all interfaces with IPs and status.",
        "hint": "show ip interface brief",
        "solution": "show ip interface brief",
        "accepted": ["show ip interface brief", "sh ip int br", "show ip int brief", "sh ip interface brief"],
        "explanation": "'show ip interface brief' is the most-used command for a quick interface health check.",
        "points": 15, "category": "basics",
    },
    {
        "id": 8, "title": "Return to Privileged Exec",
        "description": "You are deep in interface config mode. Return directly to Privileged EXEC (#) in one step.",
        "challenge": "Return to Privileged EXEC mode from any config sub-mode.",
        "hint": "Think 'end' — it jumps all the way back.",
        "solution": "end",
        "accepted": ["end", "ctrl-z"],
        "explanation": "'end' (or Ctrl-Z) returns directly to Privileged EXEC from any configuration sub-mode.",
        "points": 15, "category": "basics",
    },
    {
        "id": 9, "title": "Activate an Interface",
        "description": "By default Cisco router interfaces are administratively shut down. You must enable them.",
        "challenge": "Enable a shutdown interface (bring it up).",
        "hint": "no shutdown",
        "solution": "no shutdown",
        "accepted": ["no shutdown", "no shut"],
        "explanation": "'no shutdown' removes the admin-down state. The interface can now pass traffic if a link is present.",
        "points": 15, "category": "basics",
    },
    {
        "id": 10, "title": "Detailed Interface Statistics",
        "description": "You need error counters, queue drops, and packet statistics on FastEthernet0/0.",
        "challenge": "Show detailed statistics for interface FastEthernet0/0.",
        "hint": "show interfaces fastethernet0/0",
        "solution": "show interfaces fastethernet0/0",
        "accepted": ["show interfaces fastethernet0/0", "sh int fa0/0", "show interface fa0/0"],
        "explanation": "'show interfaces' reveals input/output errors, duplex, bandwidth, and queue stats — critical for troubleshooting.",
        "points": 15, "category": "basics",
    },
    {
        "id": 11, "title": "Add Interface Description",
        "description": "Good documentation saves hours of troubleshooting. Add a description to identify WAN links.",
        "challenge": "Set the description 'WAN-to-ISP' on the current interface.",
        "hint": "description <text>",
        "solution": "description WAN-to-ISP",
        "accepted": ["description WAN-to-ISP", "description wan-to-isp"],
        "explanation": "Descriptions appear in 'show interfaces' and 'show run'. Use them everywhere.",
        "points": 20, "category": "basics",
    },
    {
        "id": 12, "title": "View ARP Table",
        "description": "You need to map IP addresses to MAC addresses to troubleshoot Layer 2/3 issues.",
        "challenge": "Display the ARP table.",
        "hint": "show arp",
        "solution": "show arp",
        "accepted": ["show arp", "sh arp", "show ip arp"],
        "explanation": "'show arp' lists IP-to-MAC bindings. Stale entries can cause connectivity issues.",
        "points": 20, "category": "basics",
    },
    {
        "id": 13, "title": "CDP Neighbor Discovery",
        "description": "Cisco Discovery Protocol lets you see directly connected Cisco devices without network diagrams.",
        "challenge": "Show all directly connected Cisco neighbors.",
        "hint": "show cdp neighbors",
        "solution": "show cdp neighbors",
        "accepted": ["show cdp neighbors", "sh cdp nei", "show cdp nei"],
        "explanation": "'show cdp neighbors' reveals neighbor hostname, interface, platform, and capabilities.",
        "points": 20, "category": "basics",
    },
    {
        "id": 14, "title": "Check CPU Utilization",
        "description": "The router seems slow. You need to determine if the CPU is the bottleneck.",
        "challenge": "Show current CPU utilization and process list.",
        "hint": "show processes cpu",
        "solution": "show processes cpu",
        "accepted": ["show processes cpu", "sh proc cpu"],
        "explanation": "'show processes cpu' shows 5-second, 1-minute, and 5-minute CPU averages plus top consumers.",
        "points": 20, "category": "basics",
    },
    {
        "id": 15, "title": "Enable Password Encryption",
        "description": "Passwords in running-config are visible in plaintext. Encrypt them.",
        "challenge": "Enable service-level password encryption.",
        "hint": "service password-encryption",
        "solution": "service password-encryption",
        "accepted": ["service password-encryption"],
        "explanation": "'service password-encryption' applies Type 7 (weak) encryption to all plaintext passwords. Use 'enable secret' for stronger protection.",
        "points": 20, "category": "security",
    },
    {
        "id": 16, "title": "View System Logs",
        "description": "Something happened on the router. Check what the log recorded.",
        "challenge": "Display the buffered system log.",
        "hint": "show logging",
        "solution": "show logging",
        "accepted": ["show logging", "sh log"],
        "explanation": "'show logging' shows buffered syslog messages. Use 'logging buffered' to enable local storage.",
        "points": 20, "category": "basics",
    },
    {
        "id": 17, "title": "View Flash Storage",
        "description": "You need to see available storage space and the IOS image filename before upgrading.",
        "challenge": "Display the contents of flash memory.",
        "hint": "show flash",
        "solution": "show flash",
        "accepted": ["show flash", "sh flash", "show flash:"],
        "explanation": "'show flash' lists IOS images and free space. The IOS file is typically .bin format.",
        "points": 20, "category": "basics",
    },
    {
        "id": 18, "title": "Show Active Users",
        "description": "You suspect unauthorized access. Check who is currently logged into the device.",
        "challenge": "Show all users currently connected to the router.",
        "hint": "show users",
        "solution": "show users",
        "accepted": ["show users", "sh users"],
        "explanation": "'show users' displays active console and VTY line sessions, including IP addresses.",
        "points": 25, "category": "security",
    },
    {
        "id": 19, "title": "Enable Timestamps in Logs",
        "description": "Your syslog entries have no timestamps, making correlation impossible.",
        "challenge": "Enable date/time timestamps on all log messages.",
        "hint": "service timestamps log datetime",
        "solution": "service timestamps log datetime",
        "accepted": ["service timestamps log datetime", "service timestamps log datetime msec"],
        "explanation": "Timestamps are essential for correlating events with security incidents. Always enable them.",
        "points": 25, "category": "security",
    },
    {
        "id": 20, "title": "Erase Startup Configuration",
        "description": "You are decommissioning a router and must wipe its saved configuration.",
        "challenge": "Delete the startup configuration from NVRAM.",
        "hint": "erase startup-config",
        "solution": "erase startup-config",
        "accepted": ["erase startup-config", "erase start", "write erase"],
        "explanation": "'erase startup-config' clears NVRAM. The device will boot to factory defaults after the next reload.",
        "points": 25, "category": "basics",
    },

    # =========================================================
    # TIER 2 (21-40): IP Addressing, DHCP & DNS
    # =========================================================
    {
        "id": 21, "title": "Assign IP Address",
        "description": "Configure an IP address on the interface you are currently in.",
        "challenge": "Assign IP 192.168.1.1 with mask 255.255.255.0 to the current interface.",
        "hint": "ip address <ip> <mask>",
        "solution": "ip address 192.168.1.1 255.255.255.0",
        "accepted": ["ip address 192.168.1.1 255.255.255.0"],
        "explanation": "'ip address' sets the Layer 3 address. Without it the interface passes no routed traffic.",
        "points": 25, "category": "ip",
    },
    {
        "id": 22, "title": "Set Default Gateway (Switch)",
        "description": "A Layer 2 switch needs a default gateway to reach remote subnets for management.",
        "challenge": "Set the default gateway to 192.168.1.1 on a switch.",
        "hint": "ip default-gateway <ip>",
        "solution": "ip default-gateway 192.168.1.1",
        "accepted": ["ip default-gateway 192.168.1.1"],
        "explanation": "'ip default-gateway' is used on Layer 2 switches. Routers use default routes instead.",
        "points": 25, "category": "ip",
    },
    {
        "id": 23, "title": "Create a Loopback Interface",
        "description": "Loopbacks are always up and commonly used as router IDs and management IPs.",
        "challenge": "Enter the configuration mode for Loopback interface 0.",
        "hint": "interface loopback 0",
        "solution": "interface loopback 0",
        "accepted": ["interface loopback 0", "int loopback 0", "int lo0", "interface lo0"],
        "explanation": "Loopback interfaces never go down and provide stable endpoints for routing protocols and SSH management.",
        "points": 25, "category": "ip",
    },
    {
        "id": 24, "title": "Show Routing Table",
        "description": "You need to see all known routes to verify reachability.",
        "challenge": "Display the complete IP routing table.",
        "hint": "show ip route",
        "solution": "show ip route",
        "accepted": ["show ip route", "sh ip route", "sh ip ro"],
        "explanation": "'show ip route' is the single most important verification command for routing. Letters: C=connected, S=static, O=OSPF, B=BGP.",
        "points": 25, "category": "routing",
    },
    {
        "id": 25, "title": "Add a Default Route",
        "description": "Your router has no internet route. Add a static default route via the ISP gateway 203.0.113.1.",
        "challenge": "Add a static default route pointing to gateway 203.0.113.1.",
        "hint": "ip route 0.0.0.0 0.0.0.0 <gateway>",
        "solution": "ip route 0.0.0.0 0.0.0.0 203.0.113.1",
        "accepted": ["ip route 0.0.0.0 0.0.0.0 203.0.113.1"],
        "explanation": "0.0.0.0/0 matches any destination. This is the 'gateway of last resort' for unknown destinations.",
        "points": 30, "category": "routing",
    },
    {
        "id": 26, "title": "Test Connectivity",
        "description": "After configuring a new link, verify end-to-end reachability.",
        "challenge": "Send 5 ICMP echo requests to 10.0.0.1.",
        "hint": "ping 10.0.0.1",
        "solution": "ping 10.0.0.1",
        "accepted": ["ping 10.0.0.1"],
        "explanation": "'ping' sends ICMP echo requests. Five !!!!!= success, .....= failure (timeout).",
        "points": 30, "category": "troubleshooting",
    },
    {
        "id": 27, "title": "Trace the Path",
        "description": "Packets are reaching the wrong hop. Trace the exact path to 10.1.1.1.",
        "challenge": "Perform a traceroute to 10.1.1.1.",
        "hint": "traceroute 10.1.1.1",
        "solution": "traceroute 10.1.1.1",
        "accepted": ["traceroute 10.1.1.1", "trace 10.1.1.1", "tracert 10.1.1.1"],
        "explanation": "'traceroute' sends probe packets with increasing TTL to reveal each hop. Essential for diagnosing routing loops.",
        "points": 30, "category": "troubleshooting",
    },
    {
        "id": 28, "title": "Create a DHCP Pool",
        "description": "Configure the router to hand out IP addresses to clients on the LAN.",
        "challenge": "Create a DHCP pool named OFFICE.",
        "hint": "ip dhcp pool <name>",
        "solution": "ip dhcp pool OFFICE",
        "accepted": ["ip dhcp pool OFFICE", "ip dhcp pool office"],
        "explanation": "This enters DHCP pool configuration. You then set network, default-router, dns-server, and lease.",
        "points": 30, "category": "dhcp",
    },
    {
        "id": 29, "title": "Set DHCP Network",
        "description": "Inside the DHCP pool you created, specify which network to serve.",
        "challenge": "Set the DHCP pool to serve network 10.10.10.0/24.",
        "hint": "network <network> <mask>",
        "solution": "network 10.10.10.0 255.255.255.0",
        "accepted": ["network 10.10.10.0 255.255.255.0"],
        "explanation": "'network' defines the address range the DHCP pool will assign from.",
        "points": 30, "category": "dhcp",
    },
    {
        "id": 30, "title": "Set DHCP Default Gateway",
        "description": "Clients need to know their gateway. Configure it in the DHCP pool.",
        "challenge": "Set the DHCP default router to 10.10.10.1.",
        "hint": "default-router <ip>",
        "solution": "default-router 10.10.10.1",
        "accepted": ["default-router 10.10.10.1"],
        "explanation": "'default-router' is sent to DHCP clients as Option 3. Without it clients can't reach remote networks.",
        "points": 30, "category": "dhcp",
    },
    {
        "id": 31, "title": "Set DHCP DNS Server",
        "description": "Clients also need DNS. Add Google's DNS to the DHCP pool.",
        "challenge": "Set the DHCP DNS server to 8.8.8.8.",
        "hint": "dns-server <ip>",
        "solution": "dns-server 8.8.8.8",
        "accepted": ["dns-server 8.8.8.8"],
        "explanation": "'dns-server' is sent as DHCP Option 6. You can specify up to 8 DNS server IPs.",
        "points": 30, "category": "dhcp",
    },
    {
        "id": 32, "title": "Exclude DHCP Addresses",
        "description": "Servers and router interfaces need static IPs. Exclude the first 10 addresses of 192.168.0.0/24.",
        "challenge": "Exclude addresses 192.168.0.1 through 192.168.0.10 from DHCP assignment.",
        "hint": "ip dhcp excluded-address <start> <end>",
        "solution": "ip dhcp excluded-address 192.168.0.1 192.168.0.10",
        "accepted": ["ip dhcp excluded-address 192.168.0.1 192.168.0.10"],
        "explanation": "Always exclude static addresses BEFORE creating the pool. This prevents duplicate IP conflicts.",
        "points": 35, "category": "dhcp",
    },
    {
        "id": 33, "title": "View DHCP Bindings",
        "description": "Verify which devices have received DHCP leases.",
        "challenge": "Display all current DHCP address bindings.",
        "hint": "show ip dhcp binding",
        "solution": "show ip dhcp binding",
        "accepted": ["show ip dhcp binding", "sh ip dhcp binding", "show ip dhcp bindings"],
        "explanation": "'show ip dhcp binding' lists MAC-to-IP assignments, expiry times, and client hostnames.",
        "points": 35, "category": "dhcp",
    },
    {
        "id": 34, "title": "DHCP Relay Agent",
        "description": "Clients on VLAN 20 need DHCP from a server at 172.16.1.100. Configure the relay.",
        "challenge": "Set the DHCP helper address to 172.16.1.100 on the current interface.",
        "hint": "ip helper-address <server-ip>",
        "solution": "ip helper-address 172.16.1.100",
        "accepted": ["ip helper-address 172.16.1.100"],
        "explanation": "'ip helper-address' forwards broadcast DHCP requests as unicast to the server. Also forwards DNS, TFTP, and other services.",
        "points": 35, "category": "dhcp",
    },
    {
        "id": 35, "title": "Set Domain Name",
        "description": "Configure the router's DNS domain for hostname resolution.",
        "challenge": "Set the IP domain name to corp.example.com.",
        "hint": "ip domain-name <name>",
        "solution": "ip domain-name corp.example.com",
        "accepted": ["ip domain-name corp.example.com"],
        "explanation": "'ip domain-name' is needed for SSH key generation and hostname resolution.",
        "points": 35, "category": "ip",
    },
    {
        "id": 36, "title": "Configure DNS Server",
        "description": "The router needs to resolve hostnames. Point it to an internal DNS server.",
        "challenge": "Set the DNS name-server to 192.168.10.53.",
        "hint": "ip name-server <ip>",
        "solution": "ip name-server 192.168.10.53",
        "accepted": ["ip name-server 192.168.10.53"],
        "explanation": "'ip name-server' configures DNS resolution. Up to 6 servers can be specified.",
        "points": 35, "category": "ip",
    },
    {
        "id": 37, "title": "Set NTP Server",
        "description": "All devices must be time-synchronized for log correlation and certificate validity.",
        "challenge": "Configure NTP to synchronize from server 192.168.1.123.",
        "hint": "ntp server <ip>",
        "solution": "ntp server 192.168.1.123",
        "accepted": ["ntp server 192.168.1.123"],
        "explanation": "'ntp server' points the device to a time source. Accurate time is critical for syslog and crypto.",
        "points": 35, "category": "management",
    },
    {
        "id": 38, "title": "Verify NTP Status",
        "description": "Check that NTP has synchronized successfully.",
        "challenge": "Show the NTP synchronization status.",
        "hint": "show ntp status",
        "solution": "show ntp status",
        "accepted": ["show ntp status", "sh ntp status"],
        "explanation": "Look for 'Clock is synchronized'. An asterisk (*) next to a peer in 'show ntp associations' means it is the current reference.",
        "points": 40, "category": "management",
    },
    {
        "id": 39, "title": "Serial Interface Clock Rate",
        "description": "On a back-to-back serial link, the DCE end must provide the clock signal.",
        "challenge": "Set the clock rate to 128000 bps on the current serial interface.",
        "hint": "clock rate <bps>",
        "solution": "clock rate 128000",
        "accepted": ["clock rate 128000", "clock rate 128 000"],
        "explanation": "'clock rate' is configured on the DCE (provider) side only. The DTE end automatically syncs to it.",
        "points": 40, "category": "wan",
    },
    {
        "id": 40, "title": "Static Route with Exit Interface",
        "description": "Add a host route for 10.5.5.5/32 pointing out FastEthernet0/1.",
        "challenge": "Add a static route to host 10.5.5.5/32 using FastEthernet0/1 as exit interface.",
        "hint": "ip route 10.5.5.5 255.255.255.255 FastEthernet0/1",
        "solution": "ip route 10.5.5.5 255.255.255.255 FastEthernet0/1",
        "accepted": ["ip route 10.5.5.5 255.255.255.255 FastEthernet0/1", "ip route 10.5.5.5 255.255.255.255 fa0/1"],
        "explanation": "You can specify either a next-hop IP or an exit interface (or both). Using an interface alone on Ethernet can cause ARP issues — prefer next-hop IP.",
        "points": 40, "category": "routing",
    },

    # =========================================================
    # TIER 3 (41-60): Dynamic Routing (OSPF, RIP, BGP)
    # =========================================================
    {
        "id": 41, "title": "Enable OSPF Process",
        "description": "Configure OSPF with process ID 1 to enable dynamic routing.",
        "challenge": "Enable OSPF with process ID 1.",
        "hint": "router ospf 1",
        "solution": "router ospf 1",
        "accepted": ["router ospf 1"],
        "explanation": "'router ospf 1' enters OSPF configuration mode. Process ID is locally significant only (different from router-ID).",
        "points": 40, "category": "ospf",
    },
    {
        "id": 42, "title": "OSPF Network Statement",
        "description": "Tell OSPF to advertise the 192.168.1.0/24 network in area 0.",
        "challenge": "Add network 192.168.1.0/24 to OSPF area 0 using wildcard mask.",
        "hint": "network 192.168.1.0 0.0.0.255 area 0",
        "solution": "network 192.168.1.0 0.0.0.255 area 0",
        "accepted": ["network 192.168.1.0 0.0.0.255 area 0"],
        "explanation": "OSPF uses wildcard masks (inverse of subnet mask). Area 0 is the backbone — all other areas must connect to it.",
        "points": 40, "category": "ospf",
    },
    {
        "id": 43, "title": "Set OSPF Router ID",
        "description": "For stability, set an explicit OSPF router ID instead of relying on interface IPs.",
        "challenge": "Set the OSPF router ID to 1.1.1.1.",
        "hint": "router-id 1.1.1.1",
        "solution": "router-id 1.1.1.1",
        "accepted": ["router-id 1.1.1.1"],
        "explanation": "Router ID uniquely identifies the router in OSPF. Without an explicit ID, IOS picks the highest IP of active interfaces.",
        "points": 40, "category": "ospf",
    },
    {
        "id": 44, "title": "View OSPF Neighbors",
        "description": "After enabling OSPF, verify neighbor relationships have formed.",
        "challenge": "Display the OSPF neighbor table.",
        "hint": "show ip ospf neighbor",
        "solution": "show ip ospf neighbor",
        "accepted": ["show ip ospf neighbor", "sh ip ospf nei", "show ip ospf neighbors"],
        "explanation": "Look for 'FULL' state — this means the database has been synchronized. 'EXSTART' indicates a problem.",
        "points": 40, "category": "ospf",
    },
    {
        "id": 45, "title": "Passive Interface OSPF",
        "description": "The router's LAN interface should not form OSPF adjacencies but still advertise the network.",
        "challenge": "Make GigabitEthernet0/1 passive in OSPF.",
        "hint": "passive-interface GigabitEthernet0/1",
        "solution": "passive-interface GigabitEthernet0/1",
        "accepted": ["passive-interface GigabitEthernet0/1", "passive-interface gi0/1", "passive-interface gig0/1"],
        "explanation": "Passive interfaces stop sending OSPF Hellos, preventing unnecessary adjacencies on end-user segments.",
        "points": 45, "category": "ospf",
    },
    {
        "id": 46, "title": "Redistribute Default Route in OSPF",
        "description": "You want all OSPF routers to use this router as their internet gateway.",
        "challenge": "Advertise the default route into OSPF.",
        "hint": "default-information originate",
        "solution": "default-information originate",
        "accepted": ["default-information originate", "default-information originate always"],
        "explanation": "'default-information originate' injects a Type-5 LSA for 0.0.0.0/0 into OSPF. Add 'always' to advertise even without a local default.",
        "points": 45, "category": "ospf",
    },
    {
        "id": 47, "title": "View OSPF Link State Database",
        "description": "Check the OSPF topology database to understand what the router knows.",
        "challenge": "Display the OSPF link state database.",
        "hint": "show ip ospf database",
        "solution": "show ip ospf database",
        "accepted": ["show ip ospf database", "sh ip ospf database", "sh ip ospf db"],
        "explanation": "The LSDB contains Router LSAs, Network LSAs, and External LSAs. All routers in an area must have identical databases.",
        "points": 45, "category": "ospf",
    },
    {
        "id": 48, "title": "Enable RIPv2",
        "description": "Configure RIP version 2 on the router.",
        "challenge": "Enable RIP and set it to version 2.",
        "hint": "router rip → version 2",
        "solution": "version 2",
        "accepted": ["version 2"],
        "explanation": "RIPv2 supports VLSM and sends subnet masks in updates. RIPv1 is classful and obsolete.",
        "points": 45, "category": "rip",
    },
    {
        "id": 49, "title": "Disable RIP Auto-Summary",
        "description": "RIPv2 still auto-summarizes by default. Disable it to support VLSM.",
        "challenge": "Disable automatic summarization in RIP.",
        "hint": "no auto-summary",
        "solution": "no auto-summary",
        "accepted": ["no auto-summary"],
        "explanation": "'no auto-summary' lets RIPv2 advertise specific subnet routes instead of classful summaries.",
        "points": 45, "category": "rip",
    },
    {
        "id": 50, "title": "Enable BGP",
        "description": "Configure BGP for inter-AS routing. Your AS number is 65001.",
        "challenge": "Enable BGP with AS number 65001.",
        "hint": "router bgp 65001",
        "solution": "router bgp 65001",
        "accepted": ["router bgp 65001"],
        "explanation": "BGP (Border Gateway Protocol) is the internet's routing protocol. AS numbers 64512-65534 are private.",
        "points": 50, "category": "bgp",
    },
    {
        "id": 51, "title": "BGP Neighbor",
        "description": "Establish a BGP session with ISP router at 203.0.113.1, which is in AS 65002.",
        "challenge": "Add a BGP neighbor at 203.0.113.1 in AS 65002.",
        "hint": "neighbor <ip> remote-as <asn>",
        "solution": "neighbor 203.0.113.1 remote-as 65002",
        "accepted": ["neighbor 203.0.113.1 remote-as 65002"],
        "explanation": "'neighbor remote-as' defines a BGP peer. eBGP peers are in different ASes; iBGP peers share the same AS.",
        "points": 50, "category": "bgp",
    },
    {
        "id": 52, "title": "BGP Network Advertisement",
        "description": "Advertise your prefix 10.0.0.0/8 to BGP peers.",
        "challenge": "Advertise network 10.0.0.0 with mask 255.0.0.0 via BGP.",
        "hint": "network 10.0.0.0 mask 255.0.0.0",
        "solution": "network 10.0.0.0 mask 255.0.0.0",
        "accepted": ["network 10.0.0.0 mask 255.0.0.0"],
        "explanation": "BGP requires an exact match in the routing table. The 'mask' keyword is needed for non-classful prefixes.",
        "points": 50, "category": "bgp",
    },
    {
        "id": 53, "title": "BGP Summary",
        "description": "Verify BGP is working and neighbors are established.",
        "challenge": "Display the BGP neighbor summary table.",
        "hint": "show ip bgp summary",
        "solution": "show ip bgp summary",
        "accepted": ["show ip bgp summary", "sh ip bgp sum"],
        "explanation": "Look for 'Established' state and Up/Down timer. Prefixes Received column shows the number of routes learned.",
        "points": 50, "category": "bgp",
    },
    {
        "id": 54, "title": "Redistribute Connected Routes into OSPF",
        "description": "Inject all directly connected networks into OSPF so other routers learn them.",
        "challenge": "Redistribute connected routes into OSPF with subnet information.",
        "hint": "redistribute connected subnets",
        "solution": "redistribute connected subnets",
        "accepted": ["redistribute connected subnets"],
        "explanation": "'subnets' keyword is required, otherwise only classful networks are redistributed. This generates Type-5 External LSAs.",
        "points": 50, "category": "ospf",
    },
    {
        "id": 55, "title": "Enable Cisco Express Forwarding",
        "description": "CEF is Cisco's hardware-optimized forwarding mechanism. Enable it for fast routing.",
        "challenge": "Enable CEF on the router.",
        "hint": "ip cef",
        "solution": "ip cef",
        "accepted": ["ip cef"],
        "explanation": "CEF pre-builds adjacency and FIB tables so forwarding decisions happen in hardware, not the route processor.",
        "points": 50, "category": "performance",
    },
    {
        "id": 56, "title": "Show CEF Table",
        "description": "Verify the CEF Forwarding Information Base is populated.",
        "challenge": "Display the CEF forwarding table.",
        "hint": "show ip cef",
        "solution": "show ip cef",
        "accepted": ["show ip cef", "sh ip cef"],
        "explanation": "'show ip cef' reveals next-hop and adjacency info for each prefix. 'drop', 'glean', or 'receive' indicate special handling.",
        "points": 50, "category": "performance",
    },
    {
        "id": 57, "title": "OSPF Authentication",
        "description": "Secure OSPF to prevent route injection from rogue routers.",
        "challenge": "Enable MD5 authentication on OSPF area 0.",
        "hint": "area 0 authentication message-digest",
        "solution": "area 0 authentication message-digest",
        "accepted": ["area 0 authentication message-digest"],
        "explanation": "MD5 authentication prevents unauthorized OSPF neighbors. You also need 'ip ospf message-digest-key' on each interface.",
        "points": 55, "category": "ospf",
    },
    {
        "id": 58, "title": "Summarize OSPF Routes",
        "description": "Reduce the size of the routing table by summarizing area 1 routes at the ABR.",
        "challenge": "Summarize 10.1.0.0/16 range into OSPF backbone from area 1.",
        "hint": "area 1 range 10.1.0.0 255.255.0.0",
        "solution": "area 1 range 10.1.0.0 255.255.0.0",
        "accepted": ["area 1 range 10.1.0.0 255.255.0.0"],
        "explanation": "'area range' is used at ABRs to summarize inter-area routes, reducing LSA flooding and routing table size.",
        "points": 55, "category": "ospf",
    },
    {
        "id": 59, "title": "Set OSPF Hello Interval",
        "description": "Tune OSPF timers for faster convergence on the WAN link.",
        "challenge": "Set the OSPF hello interval to 5 seconds on the current interface.",
        "hint": "ip ospf hello-interval 5",
        "solution": "ip ospf hello-interval 5",
        "accepted": ["ip ospf hello-interval 5"],
        "explanation": "Hello timers must match on both ends of a link. Dead interval is 4x hello by default. Faster hellos = faster failure detection.",
        "points": 55, "category": "ospf",
    },
    {
        "id": 60, "title": "BGP Route Filtering with Prefix List",
        "description": "Filter BGP advertisements so you only accept the ISP's summary route.",
        "challenge": "Create a prefix list named ISP_ONLY that permits only 0.0.0.0/0.",
        "hint": "ip prefix-list ISP_ONLY permit 0.0.0.0/0",
        "solution": "ip prefix-list ISP_ONLY permit 0.0.0.0/0",
        "accepted": ["ip prefix-list ISP_ONLY permit 0.0.0.0/0"],
        "explanation": "Prefix lists are more efficient than ACLs for route filtering. Apply with 'neighbor X prefix-list ISP_ONLY in'.",
        "points": 55, "category": "bgp",
    },

    # =========================================================
    # TIER 4 (61-80): Switching, VLANs & Spanning Tree
    # =========================================================
    {
        "id": 61, "title": "Create a VLAN",
        "description": "Segment the network by creating VLAN 10 for the Sales department.",
        "challenge": "Create VLAN 10 on the switch.",
        "hint": "vlan 10",
        "solution": "vlan 10",
        "accepted": ["vlan 10"],
        "explanation": "'vlan 10' enters VLAN configuration mode. You can then name it and assign ports.",
        "points": 55, "category": "switching",
    },
    {
        "id": 62, "title": "Name a VLAN",
        "description": "Name VLAN 10 'SALES' for easy identification.",
        "challenge": "Set the VLAN name to SALES.",
        "hint": "name SALES",
        "solution": "name SALES",
        "accepted": ["name SALES", "name sales"],
        "explanation": "VLAN names appear in 'show vlan brief'. Good naming is essential documentation.",
        "points": 55, "category": "switching",
    },
    {
        "id": 63, "title": "Assign Access Port to VLAN",
        "description": "Connect a PC on port fa0/1 to VLAN 10.",
        "challenge": "Assign interface FastEthernet0/1 to VLAN 10 as an access port.",
        "hint": "switchport access vlan 10",
        "solution": "switchport access vlan 10",
        "accepted": ["switchport access vlan 10"],
        "explanation": "Access ports carry traffic for a single VLAN without tagging. End devices connect here.",
        "points": 55, "category": "switching",
    },
    {
        "id": 64, "title": "Set Access Mode",
        "description": "Explicitly configure the port mode to prevent DTP negotiation.",
        "challenge": "Set the current interface to access mode.",
        "hint": "switchport mode access",
        "solution": "switchport mode access",
        "accepted": ["switchport mode access"],
        "explanation": "'switchport mode access' disables DTP and locks the port as an access port. Always configure this explicitly for security.",
        "points": 60, "category": "switching",
    },
    {
        "id": 65, "title": "Configure Trunk Port",
        "description": "The link between switches needs to carry all VLANs.",
        "challenge": "Set the current interface to trunk mode.",
        "hint": "switchport mode trunk",
        "solution": "switchport mode trunk",
        "accepted": ["switchport mode trunk"],
        "explanation": "Trunk ports carry multiple VLANs using 802.1Q tagging. Used between switches and routers.",
        "points": 60, "category": "switching",
    },
    {
        "id": 66, "title": "Allow Specific VLANs on Trunk",
        "description": "Restrict the trunk to only carry VLANs 10, 20, and 99.",
        "challenge": "Allow only VLANs 10, 20, and 99 on the current trunk interface.",
        "hint": "switchport trunk allowed vlan 10,20,99",
        "solution": "switchport trunk allowed vlan 10,20,99",
        "accepted": ["switchport trunk allowed vlan 10,20,99"],
        "explanation": "By default all VLANs are allowed on trunks. Restricting reduces unnecessary traffic and attack surface.",
        "points": 60, "category": "switching",
    },
    {
        "id": 67, "title": "Show VLAN Summary",
        "description": "Verify VLAN creation and port assignments.",
        "challenge": "Display a brief summary of all VLANs.",
        "hint": "show vlan brief",
        "solution": "show vlan brief",
        "accepted": ["show vlan brief", "sh vlan br", "sh vlan brief"],
        "explanation": "'show vlan brief' lists each VLAN, its name, status, and assigned ports in a compact format.",
        "points": 60, "category": "switching",
    },
    {
        "id": 68, "title": "Show Trunk Interfaces",
        "description": "Verify which interfaces are configured as trunks and what VLANs they carry.",
        "challenge": "Display all trunk interface information.",
        "hint": "show interfaces trunk",
        "solution": "show interfaces trunk",
        "accepted": ["show interfaces trunk", "sh int trunk"],
        "explanation": "Shows encapsulation, native VLAN, allowed VLANs, and VLANs in STP forwarding state.",
        "points": 60, "category": "switching",
    },
    {
        "id": 69, "title": "Set Spanning Tree Mode",
        "description": "Enable Rapid PVST+ for faster convergence compared to classic STP.",
        "challenge": "Set the spanning tree mode to rapid-pvst.",
        "hint": "spanning-tree mode rapid-pvst",
        "solution": "spanning-tree mode rapid-pvst",
        "accepted": ["spanning-tree mode rapid-pvst"],
        "explanation": "Rapid PVST+ converges in 1-2 seconds vs. 30-50 seconds for traditional STP. Use it in all modern networks.",
        "points": 60, "category": "stp",
    },
    {
        "id": 70, "title": "Set Root Bridge",
        "description": "Make this switch the root bridge for VLAN 10 to control traffic flow.",
        "challenge": "Set this switch as the primary root bridge for VLAN 10.",
        "hint": "spanning-tree vlan 10 root primary",
        "solution": "spanning-tree vlan 10 root primary",
        "accepted": ["spanning-tree vlan 10 root primary"],
        "explanation": "'root primary' sets the bridge priority to 24576 (or lower if needed), making this switch the root.",
        "points": 65, "category": "stp",
    },
    {
        "id": 71, "title": "Enable Port Security",
        "description": "Prevent unauthorized devices from connecting on fa0/10.",
        "challenge": "Enable port security on the current interface.",
        "hint": "switchport port-security",
        "solution": "switchport port-security",
        "accepted": ["switchport port-security"],
        "explanation": "Port security limits the number of MAC addresses on a port. Must be an access port first.",
        "points": 65, "category": "security",
    },
    {
        "id": 72, "title": "Set Max MAC Addresses",
        "description": "Allow a maximum of 2 MAC addresses on the secured port.",
        "challenge": "Set port security maximum to 2 MAC addresses.",
        "hint": "switchport port-security maximum 2",
        "solution": "switchport port-security maximum 2",
        "accepted": ["switchport port-security maximum 2"],
        "explanation": "Default maximum is 1. Increase for IP phones that share a port with a PC.",
        "points": 65, "category": "security",
    },
    {
        "id": 73, "title": "Port Security Violation Mode",
        "description": "Configure what happens when a violation occurs — shutdown mode is too disruptive.",
        "challenge": "Set port security violation mode to restrict.",
        "hint": "switchport port-security violation restrict",
        "solution": "switchport port-security violation restrict",
        "accepted": ["switchport port-security violation restrict"],
        "explanation": "Modes: shutdown (default, disables port) | restrict (drops, logs, increments counter) | protect (drops silently).",
        "points": 65, "category": "security",
    },
    {
        "id": 74, "title": "Show Port Security",
        "description": "Verify port security configuration and see if any violations have occurred.",
        "challenge": "Display port security status for interface FastEthernet0/1.",
        "hint": "show port-security interface FastEthernet0/1",
        "solution": "show port-security interface FastEthernet0/1",
        "accepted": ["show port-security interface FastEthernet0/1", "sh port-security int fa0/1"],
        "explanation": "Shows max/current MACs, violation count, and violation mode. High violation count indicates an attack.",
        "points": 65, "category": "security",
    },
    {
        "id": 75, "title": "Create a Switch Virtual Interface (SVI)",
        "description": "Create a Layer 3 gateway for VLAN 10 on the multilayer switch.",
        "challenge": "Enter configuration mode for VLAN 10 SVI.",
        "hint": "interface vlan 10",
        "solution": "interface vlan 10",
        "accepted": ["interface vlan 10", "int vlan 10"],
        "explanation": "SVIs are virtual Layer 3 interfaces for VLANs. They provide inter-VLAN routing on multilayer switches.",
        "points": 70, "category": "switching",
    },
    {
        "id": 76, "title": "Enable IP Routing on Switch",
        "description": "Enable Layer 3 routing capability on a multilayer switch.",
        "challenge": "Enable IP routing on the multilayer switch.",
        "hint": "ip routing",
        "solution": "ip routing",
        "accepted": ["ip routing"],
        "explanation": "'ip routing' is required on Catalyst multilayer switches to enable inter-VLAN routing via SVIs.",
        "points": 70, "category": "switching",
    },
    {
        "id": 77, "title": "Show MAC Address Table",
        "description": "Find which port a device with a specific MAC address is connected to.",
        "challenge": "Display the MAC address table.",
        "hint": "show mac address-table",
        "solution": "show mac address-table",
        "accepted": ["show mac address-table", "sh mac add", "show mac-address-table"],
        "explanation": "The MAC table maps MAC addresses to switch ports. 'dynamic' entries are learned; 'static' are configured.",
        "points": 70, "category": "switching",
    },
    {
        "id": 78, "title": "EtherChannel — LACP Active",
        "description": "Bundle fa0/1 and fa0/2 into a link aggregation group using LACP.",
        "challenge": "Add the current interface to EtherChannel group 1 using LACP active mode.",
        "hint": "channel-group 1 mode active",
        "solution": "channel-group 1 mode active",
        "accepted": ["channel-group 1 mode active"],
        "explanation": "LACP active negotiates the bundle. Both ends should be 'active' or one can be 'passive'. Doubles bandwidth and provides redundancy.",
        "points": 70, "category": "switching",
    },
    {
        "id": 79, "title": "Show EtherChannel Status",
        "description": "Verify EtherChannel has formed correctly.",
        "challenge": "Display a summary of all EtherChannel port channels.",
        "hint": "show etherchannel summary",
        "solution": "show etherchannel summary",
        "accepted": ["show etherchannel summary", "sh etherchannel sum"],
        "explanation": "Look for 'P' (bundled in port-channel) next to member interfaces. 'D' means down, 'I' means standalone.",
        "points": 70, "category": "switching",
    },
    {
        "id": 80, "title": "BPDU Guard",
        "description": "Prevent STP topology changes from rogue switches connected to access ports.",
        "challenge": "Enable BPDU Guard on the current interface.",
        "hint": "spanning-tree bpduguard enable",
        "solution": "spanning-tree bpduguard enable",
        "accepted": ["spanning-tree bpduguard enable"],
        "explanation": "BPDU Guard shuts down a port if it receives a BPDU. Combined with PortFast for edge ports — essential security.",
        "points": 75, "category": "security",
    },

    # =========================================================
    # TIER 5 (81-100): Security, ACLs, NAT & VPN Hardening
    # =========================================================
    {
        "id": 81, "title": "Create a Standard ACL",
        "description": "Block all traffic from 192.168.100.0/24 using a standard named ACL.",
        "challenge": "Create a standard named ACL called BLOCK_ROGUE.",
        "hint": "ip access-list standard BLOCK_ROGUE",
        "solution": "ip access-list standard BLOCK_ROGUE",
        "accepted": ["ip access-list standard BLOCK_ROGUE", "ip access-list standard block_rogue"],
        "explanation": "Named ACLs are easier to manage than numbered ACLs. Standard ACLs filter based on source IP only.",
        "points": 75, "category": "acl",
    },
    {
        "id": 82, "title": "ACL Permit Statement",
        "description": "Inside the ACL, permit traffic from 10.0.0.0/8.",
        "challenge": "Add an ACL entry to permit source network 10.0.0.0 with wildcard 0.255.255.255.",
        "hint": "permit 10.0.0.0 0.255.255.255",
        "solution": "permit 10.0.0.0 0.255.255.255",
        "accepted": ["permit 10.0.0.0 0.255.255.255"],
        "explanation": "ACL entries are processed top-down. There is an implicit 'deny any' at the end of every ACL.",
        "points": 75, "category": "acl",
    },
    {
        "id": 83, "title": "Create Extended ACL",
        "description": "Create a named extended ACL to filter both source/destination and protocol/port.",
        "challenge": "Create an extended named ACL called WEB_FILTER.",
        "hint": "ip access-list extended WEB_FILTER",
        "solution": "ip access-list extended WEB_FILTER",
        "accepted": ["ip access-list extended WEB_FILTER", "ip access-list extended web_filter"],
        "explanation": "Extended ACLs can match protocol, source/destination IP and port, TCP flags, and DSCP values.",
        "points": 75, "category": "acl",
    },
    {
        "id": 84, "title": "ACL Permit HTTPS Only",
        "description": "Inside WEB_FILTER, only permit HTTPS traffic from any source to any destination.",
        "challenge": "Add an ACL entry to permit TCP from any to any on port 443.",
        "hint": "permit tcp any any eq 443",
        "solution": "permit tcp any any eq 443",
        "accepted": ["permit tcp any any eq 443", "permit tcp any any eq https"],
        "explanation": "'eq 443' matches destination port 443 (HTTPS). Use 'eq 80' for HTTP, 'eq 22' for SSH.",
        "points": 75, "category": "acl",
    },
    {
        "id": 85, "title": "Apply ACL to Interface",
        "description": "Apply WEB_FILTER to filter inbound traffic on FastEthernet0/0.",
        "challenge": "Apply the ACL WEB_FILTER inbound on the current interface.",
        "hint": "ip access-group WEB_FILTER in",
        "solution": "ip access-group WEB_FILTER in",
        "accepted": ["ip access-group WEB_FILTER in"],
        "explanation": "'in' filters traffic entering the interface. 'out' filters traffic leaving. Place extended ACLs close to the source.",
        "points": 80, "category": "acl",
    },
    {
        "id": 86, "title": "Verify ACL Counters",
        "description": "Check how many packets have matched each ACL entry.",
        "challenge": "Display all IP access lists with match counts.",
        "hint": "show ip access-lists",
        "solution": "show ip access-lists",
        "accepted": ["show ip access-lists", "sh ip access-lists", "show ip access-list"],
        "explanation": "Match counters show how many packets hit each ACE. Zero matches on a deny rule could indicate the rule is never reached.",
        "points": 80, "category": "acl",
    },
    {
        "id": 87, "title": "Mark NAT Inside Interface",
        "description": "Configure PAT (NAT overload). First, mark the LAN-facing interface as NAT inside.",
        "challenge": "Mark the current interface as NAT inside.",
        "hint": "ip nat inside",
        "solution": "ip nat inside",
        "accepted": ["ip nat inside"],
        "explanation": "Every NAT configuration requires interfaces marked 'inside' (LAN) and 'outside' (WAN/Internet).",
        "points": 80, "category": "nat",
    },
    {
        "id": 88, "title": "Mark NAT Outside Interface",
        "description": "Mark the WAN-facing interface as NAT outside.",
        "challenge": "Mark the current interface as NAT outside.",
        "hint": "ip nat outside",
        "solution": "ip nat outside",
        "accepted": ["ip nat outside"],
        "explanation": "Traffic from 'inside' to 'outside' is translated. Without both markers, NAT will not function.",
        "points": 80, "category": "nat",
    },
    {
        "id": 89, "title": "Configure PAT (NAT Overload)",
        "description": "Configure PAT so all inside hosts share the outside interface IP.",
        "challenge": "Configure PAT overloading using ACL 1 and the outside interface FastEthernet0/1.",
        "hint": "ip nat inside source list 1 interface FastEthernet0/1 overload",
        "solution": "ip nat inside source list 1 interface FastEthernet0/1 overload",
        "accepted": ["ip nat inside source list 1 interface FastEthernet0/1 overload",
                     "ip nat inside source list 1 interface fa0/1 overload"],
        "explanation": "PAT uses port numbers to distinguish sessions, allowing thousands of hosts to share one public IP.",
        "points": 80, "category": "nat",
    },
    {
        "id": 90, "title": "Show NAT Translations",
        "description": "Verify NAT is working by checking active translation entries.",
        "challenge": "Display all active NAT translations.",
        "hint": "show ip nat translations",
        "solution": "show ip nat translations",
        "accepted": ["show ip nat translations", "sh ip nat trans"],
        "explanation": "Shows inside local, inside global, outside local, outside global for each session.",
        "points": 80, "category": "nat",
    },
    {
        "id": 91, "title": "Configure IKE Phase 1 Policy",
        "description": "Set up an IKEv1 ISAKMP policy for a site-to-site VPN.",
        "challenge": "Create an ISAKMP policy with priority 10.",
        "hint": "crypto isakmp policy 10",
        "solution": "crypto isakmp policy 10",
        "accepted": ["crypto isakmp policy 10"],
        "explanation": "IKE Phase 1 negotiates the ISAKMP SA (security association). Lower priority number = preferred policy.",
        "points": 85, "category": "vpn",
    },
    {
        "id": 92, "title": "Set VPN Encryption",
        "description": "Inside the ISAKMP policy, configure AES-256 encryption.",
        "challenge": "Set the encryption algorithm to AES-256.",
        "hint": "encryption aes 256",
        "solution": "encryption aes 256",
        "accepted": ["encryption aes 256"],
        "explanation": "AES-256 provides strong symmetric encryption for IKE Phase 1. Avoid 3DES on modern systems.",
        "points": 85, "category": "vpn",
    },
    {
        "id": 93, "title": "Set VPN Authentication",
        "description": "Configure pre-shared key authentication for the VPN.",
        "challenge": "Set the IKE authentication method to pre-share.",
        "hint": "authentication pre-share",
        "solution": "authentication pre-share",
        "accepted": ["authentication pre-share"],
        "explanation": "Pre-shared keys are simple but must be kept secret. For scalable deployments use PKI certificates instead.",
        "points": 85, "category": "vpn",
    },
    {
        "id": 94, "title": "VPN Pre-Shared Key",
        "description": "Configure the pre-shared key for the peer at 203.0.113.100.",
        "challenge": "Set the ISAKMP pre-shared key 'S3cur3K3y!' for peer 203.0.113.100.",
        "hint": "crypto isakmp key <key> address <peer-ip>",
        "solution": "crypto isakmp key S3cur3K3y! address 203.0.113.100",
        "accepted": ["crypto isakmp key S3cur3K3y! address 203.0.113.100"],
        "explanation": "The key must match on both VPN peers. Never use dictionary words — use long random passphrases.",
        "points": 85, "category": "vpn",
    },
    {
        "id": 95, "title": "Encrypt All Passwords",
        "description": "Running-config shows passwords in cleartext. Encrypt them all.",
        "challenge": "Enable password encryption across all configured passwords.",
        "hint": "service password-encryption",
        "solution": "service password-encryption",
        "accepted": ["service password-encryption"],
        "explanation": "Applies Type 7 encoding. While not cryptographically strong, it prevents casual shoulder-surfing. Use 'enable secret' (Type 5/9) for privileged access.",
        "points": 85, "category": "hardening",
    },
    {
        "id": 96, "title": "Login Warning Banner",
        "description": "Legal requires a warning banner before authentication.",
        "challenge": "Set a MOTD banner with the delimiter # and text 'AUTHORIZED ACCESS ONLY'.",
        "hint": "banner motd # AUTHORIZED ACCESS ONLY #",
        "solution": "banner motd # AUTHORIZED ACCESS ONLY #",
        "accepted": ["banner motd # AUTHORIZED ACCESS ONLY #", "banner motd #AUTHORIZED ACCESS ONLY#"],
        "explanation": "MOTD banners are displayed before login. Without a warning banner, prosecuting unauthorized access may be legally difficult.",
        "points": 90, "category": "hardening",
    },
    {
        "id": 97, "title": "Disable HTTP Management",
        "description": "The HTTP server exposes management access over an unencrypted channel. Disable it.",
        "challenge": "Disable the HTTP server on the router.",
        "hint": "no ip http server",
        "solution": "no ip http server",
        "accepted": ["no ip http server"],
        "explanation": "Use 'ip http secure-server' for HTTPS management. Disable plain HTTP to prevent credential sniffing.",
        "points": 90, "category": "hardening",
    },
    {
        "id": 98, "title": "Enforce Minimum Password Length",
        "description": "Weak passwords are a major vulnerability. Enforce a minimum length policy.",
        "challenge": "Set the minimum password length to 12 characters.",
        "hint": "security passwords min-length 12",
        "solution": "security passwords min-length 12",
        "accepted": ["security passwords min-length 12"],
        "explanation": "This rejects passwords shorter than 12 characters at configuration time. Combine with 'login block-for' for lockout.",
        "points": 90, "category": "hardening",
    },
    {
        "id": 99, "title": "SSH Brute Force Protection",
        "description": "Block login attempts after 3 failures in 60 seconds for 120 seconds.",
        "challenge": "Configure login block-for 120 attempts 3 within 60.",
        "hint": "login block-for <secs> attempts <n> within <secs>",
        "solution": "login block-for 120 attempts 3 within 60",
        "accepted": ["login block-for 120 attempts 3 within 60"],
        "explanation": "This activates quiet mode: 3 failures in 60 seconds blocks all logins for 120 seconds. Effective against brute-force attacks.",
        "points": 90, "category": "hardening",
    },
    {
        "id": 100, "title": "The Grand Cisco Audit",
        "description": "Final challenge: run the built-in Cisco IOS security audit command to check the device hardening posture.",
        "challenge": "Run the Cisco IOS AutoSecure audit to review current security settings.",
        "hint": "auto secure",
        "solution": "auto secure",
        "accepted": ["auto secure", "autosecure"],
        "explanation": "'auto secure' (AutoSecure) interactively reviews and fixes common IOS security misconfigurations — from disabling unneeded services to enforcing SSH and AAA. You are now a Cisco Security Engineer! 🏆",
        "points": 150, "category": "hardening",
    },
]


# ---------------------------------------------------------------------------
# Visual identity
# ---------------------------------------------------------------------------

def show_banner() -> None:
    banner = """
    ╔═══════════════════════════════════════════════════════════════╗
    ║                                                               ║
    ║   ██████╗██╗███████╗ ██████╗ ██████╗  ██████╗ ██╗   ██╗███████╗╗║
    ║  ██╔════╝██║██╔════╝██╔════╝██╔═══██╗██╔═══██╗██║   ██║██╔════╝║
    ║  ██║     ██║███████╗██║     ██║   ██║██║   ██║██║   ██║█████╗  ║
    ║  ██║     ██║╚════██║██║     ██║   ██║██║▄▄ ██║██║   ██║██╔══╝  ║
    ║  ╚██████╗██║███████║╚██████╗╚██████╔╝╚██████╔╝╚██████╔╝███████╗║
    ║   ╚═════╝╚═╝╚══════╝ ╚═════╝ ╚═════╝  ╚══▀▀═╝  ╚═════╝╚══════╝║
    ║                                                               ║
    ║            📡 Cisco IOS & Network Security Mastery 📡         ║
    ║              100 Levels · From CLI Rookie to CCIE             ║
    ║                     Author: arkanzasfeziii                    ║
    ║                                                               ║
    ╚═══════════════════════════════════════════════════════════════╝
    """
    console.print(f"[bright_blue]{banner}[/]")
    time.sleep(0.8)


def simulate_boot() -> None:
    msgs = [
        "Loading IOS image...",
        "Initializing hardware...",
        "Setting up interfaces...",
        "Loading startup-config...",
        "System ready!",
    ]
    with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), console=console) as p:
        task = p.add_task("[cyan]Booting IOS…", total=len(msgs))
        for msg in msgs:
            p.update(task, description=f"[bright_blue]{msg}")
            time.sleep(random.uniform(0.25, 0.55))
            p.advance(task)


def run() -> None:
    from games.base import run_game
    run_game(
        levels=LEVELS,
        ranks=RANKS,
        colors=COLORS,
        save_file=SAVE_FILE,
        game_name=GAME_NAME,
        show_banner_fn=show_banner,
        simulate_boot_fn=simulate_boot,
        engine=ENGINE,
        achievement_thresholds=ACHIEVEMENTS,
    )


if __name__ == "__main__":
    run()
